language: python
python: '3.6'
services: postgresql
install: pip install -r requirements.txt
script: python manage.py test
notifications:
  slack:
    secure: hfOa+cRjg0jz28TLhh4ZqWSztqKOdCiV8DsudVNZI6Z7ZfWCsBUmn4vleVJI3e7cf+WoJ3YvPA/l/aJp0FAVWXp/CGUG+alYA34rMx7LXxHa1+3bCCynFIPXTkmYCgHK5rborG/ARrlkx/AaT1sfbeMljpndK6esUXj1PSfeE0ksK1XbCd2jbYAeiBwduy7mPErHZj2wnnRlgO80Q3HrqeUWRSYtxaWn/bueO/LVSdjNlXcRUEXZ+omeQGmjuoEQctCpa8ysvm+q7xdrYvuvlKsLnvLo5lmNxPcK93BaS5DXLbVrx3W9jdVdGkDQK9Qmv2V6Dwx8jFB279f9XYiRtdTbdwumYCIqXsFu3y14850u6So6nxshy2MxJcY+ljPMClkm6RIo+qrAaPk9Tw3+Gu8svfGnvCwuLwbJLdz85850XaZKgtWBdrwDIiZrRGDTMGKp/o2gE24eqJ2wbu/tQdz4cIYhb7j/4+Yt9WS35lsKh9rXkxGcSwZKN+e1QwC/TCf55+YC6xc95/cBMwhp1djGlDUmRKaoZhLYHwIYTJcNBDoURIYB7IObdPU92e0sqosxRkOAoy0hvu8qSBztsEApQdiOyp0ysclc6HYRKwQd5a3FT7whhaagsaGg+zI/u+GNYNdVidfCLTzTgbX7mc4nW/bGvMB9n7edvsyeSd4=
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIN4WRUDR2MV6ZXJA
  secret_access_key:
    secure: Y7GoA8KUe3ab2+cIVnDfF359qrkPlLGBfCiz3Y83WxSR2Dum48ADMZMveVkpmrjXRzn1pLW4vZSvmz/5uUHxqwUnxq+yjRdOBbmmiPXghSrP3uk/hVe0SSpgjbnqmXcN+2H6Kwx2p0c7Jg/zesYZA3UZR1c+A8zCbPrHJqzQ2Ap7N7s/qovKK/6/2GEPg7Nc538jEDMzamJXgpTEQc24oySx/D/X4xTlmh1H3oiXvR69VhQTaqi7tsAwc7AM8c+hWVW62OCsOnbZClVZO16RcrbLvJrYIMNfBR7gjMcSwmsSesabd6anXJtZpHVteepv+3D5ng/nIXxy3M2sPn0hl47EI9gphWnFpW4P0LKLUKMAzgM5yzjprmwV6dTyWk+x3OF54vd/ceUZwsSafctYt1sPzpCjpBktVyIRvSXqvomn3Q7Rl8zl5kF4BISxFdtOQTWTA9ZEZIs2F4wlQSYsUSFe36nubTI1TkTRyitgZHBHU8lJgjacj/11fIlnqL53OGy6aWdQr1Ryko9izDwMH1PJsD8K9moK1yBWSFc1ZR6Tkhxc+wm4n7q5fv6fQuVekeHSidopO2pG3Jotpyu0m0y2Bk609t0WqE+3dQOLYxDeBU9OcCsSfAEcKxmSqFaO4lLHxwsyTEh7UHu5FCY5l4lz/cf6lf9+ZTl/jJmf1Hk=
  region: eu-west-2
  app: threat-buster
  env: threat-buster-dev
  bucket_name: elasticbeanstalk-eu-west-2-404063407815
  on:
    repo: IrdetoServices/threat-buster
    branch: develop
