# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('landing', '0002_auto_20170706_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='tenant',
        ),
        migrations.AlterModelOptions(
            name='childcategory',
            options={'ordering': ['order'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='parentcategory',
            options={'ordering': ['order'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='childcategory',
            old_name='parentCategory',
            new_name='parent_category',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='plan',
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
