# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 11:50
from __future__ import unicode_literals

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('landing', '0003_auto_20170711_0947'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='surveyresults',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='auth.Group'),
        ),
    ]
